EARLY_STOPPAGE = 12
EPOCHS = 50

# LSTM Optimized Hyperparameters (from Optuna optimization)
LSTM_HIDDEN_SIZE = 80
LSTM_NUM_LAYERS = 3
LSTM_DROPOUT = 0.4
LSTM_LEARNING_RATE = 0.0007
LSTM_WEIGHT_DECAY = 0.0001
LSTM_BATCH_SIZE = 64
LSTM_LR_SCHEDULER_PATIENCE = 6
LSTM_LR_SCHEDULER_FACTOR = 0.5
LSTM_MAX_GRAD_NORM = 0.6

# GRU Optimized Hyperparameters (from Optuna optimization)
GRU_HIDDEN_SIZE = 96
GRU_NUM_LAYERS = 2
GRU_DROPOUT = 0.3
GRU_LEARNING_RATE = 0.001
GRU_WEIGHT_DECAY = 0.0001
GRU_BATCH_SIZE = 32
GRU_LR_SCHEDULER_PATIENCE = 6
GRU_LR_SCHEDULER_FACTOR = 0.5
GRU_MAX_GRAD_NORM = 0.6

# Bi-LSTM Optimized Hyperparameters (from Optuna optimization)
BI_LSTM_HIDDEN_SIZE = 96
BI_LSTM_NUM_LAYERS = 2
BI_LSTM_DROPOUT = 0.2
BI_LSTM_LEARNING_RATE = 0.0015
BI_LSTM_WEIGHT_DECAY = 0.0001
BI_LSTM_BATCH_SIZE = 48
BI_LSTM_LR_SCHEDULER_PATIENCE = 6
BI_LSTM_LR_SCHEDULER_FACTOR = 0.5
BI_LSTM_MAX_GRAD_NORM = 0.6
