EARLY_STOPPAGE = 12
EPOCHS = 50

# LSTM Optimized Hyperparameters (from Optuna optimization)
LSTM_HIDDEN_SIZE = 80
LSTM_NUM_LAYERS = 3
LSTM_DROPOUT = 0.4
LSTM_LEARNING_RATE = 0.0007
LSTM_WEIGHT_DECAY = 0.0001
LSTM_BATCH_SIZE = 64
LSTM_LR_SCHEDULER_PATIENCE = 6
LSTM_LR_SCHEDULER_FACTOR = 0.5
LSTM_MAX_GRAD_NORM = 0.6

# GRU Optimized Hyperparameters (from Optuna optimization)
GRU_HIDDEN_SIZE = 96
GRU_NUM_LAYERS = 2
GRU_DROPOUT = 0.3
GRU_LEARNING_RATE = 0.001
GRU_WEIGHT_DECAY = 0.0001
GRU_BATCH_SIZE = 32
GRU_LR_SCHEDULER_PATIENCE = 6
GRU_LR_SCHEDULER_FACTOR = 0.5
GRU_MAX_GRAD_NORM = 0.6

# Bi-LSTM Optimized Hyperparameters (from Optuna optimization)
BI_LSTM_HIDDEN_SIZE = 96
BI_LSTM_NUM_LAYERS = 2
BI_LSTM_DROPOUT = 0.2
BI_LSTM_LEARNING_RATE = 0.0015
BI_LSTM_WEIGHT_DECAY = 0.0001
BI_LSTM_BATCH_SIZE = 48
BI_LSTM_LR_SCHEDULER_PATIENCE = 6
BI_LSTM_LR_SCHEDULER_FACTOR = 0.5
BI_LSTM_MAX_GRAD_NORM = 0.6

# CNN Optimized Hyperparameters (from Optuna optimization - Val Loss: 0.8447)
CNN_CONV1_CHANNELS = 32
CNN_CONV2_CHANNELS = 128
CNN_CONV3_CHANNELS = 96
CNN_KERNEL_SIZE_1 = 3
CNN_KERNEL_SIZE_2 = 3
CNN_KERNEL_SIZE_3 = 2
CNN_FC_SIZE_1 = 96
CNN_FC_SIZE_2 = 16
CNN_DROPOUT = 0.3
CNN_LEARNING_RATE = 0.0015
CNN_WEIGHT_DECAY = 0.0001
CNN_BATCH_SIZE = 64
CNN_LR_SCHEDULER_PATIENCE = 6
CNN_LR_SCHEDULER_FACTOR = 0.5
CNN_MAX_GRAD_NORM = 0.6
